export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

export const ADD_PRODUCT_ADMIN = "ADD_PRODUCT_ADMIN";
export const ADD_PRODUCT_ADMIN_SUCCESS = "ADD_PRODUCT_ADMIN_SUCCESS";

export const DELETE_PRODUCT_ADMIN = "DELETE_PRODUCT_ADMIN";
export const DELETE_PRODUCT_ADMIN_SUCCESS = "DELETE_PRODUCT_ADMIN_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM__CART_SUCCESS = "REMOVE_FROM__CART_SUCCESS";
